services:
  database:
    image: postgres:17-alpine
    container_name: autodeployer-db 
    environment:
      POSTGRES_USER: tad
      POSTGRES_PASSWORD: tAd@123
      POSTGRES_DB: autodeployer 

  server:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: autodeployer-backend
    depends_on:
      - database
    ports:
      - "8000:8000"
